---
- name: Playbook to generate a keypair in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create the pcorneli keypair
      ec2_key:
        name: tdeborge
        state: absent
