---
- name: Playbook to generate a keypair in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create the tdeborge keypair
      ec2_key:
        name: tdeborge
        region: eu-west-1
      register: keypair

    - name: Write private key to a file
      copy:
        dest: ../files/tdeborge.pem
        content: "{{ keypair.key.private_key }}"
        mode: 0600
      when: keypair.changed
